config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations",  confirmations: 'confirmations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get 'load_cities' => 'welcome#load_cities'
  get 'load_state' => 'welcome#load_state'

  resources :bsp_trainings
  resources :llc_services
  resources :medications
  resources :medication_counts
  resources :mars
  resources :behaviors

  resources :users do
    get 'settings'
    get 'edit_password', on: :collection
    put 'update_password', on: :collection
    post 'add_individual', on: :collection
    put 'update_individual', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/behavior.rb
class Behavior < ApplicationRecord
  belongs_to :user

  has_one :restricted_measure, dependent: :destroy
  accepts_nested_attributes_for :restricted_measure

  has_many :behavior_outcomes, dependent: :destroy
  accepts_nested_attributes_for :behavior_outcomes, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank
end

app/models/behavior_outcome.rb
class BehaviorOutcome < ApplicationRecord
  belongs_to :behavior
end

app/models/bsp_training.rb
class BspTraining < ApplicationRecord
   belongs_to :company
  belongs_to :user
end

app/models/change_service.rb
class ChangeService < ApplicationRecord
  belongs_to :change_serviceable, polymorphic: true, optional: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :bsp_trainings
  has_many :llc_services
  has_many :medications
  has_many :medication_counts
  has_many :mars
  has_many :behaviors

  def individuals
    self.users.where(admin: false)
  end
end

app/models/hpc_service.rb
class HpcService < ApplicationRecord
  belongs_to :hpc_serviceable, polymorphic: true, optional: true
end

app/models/ist_information.rb
class IstInformation < ApplicationRecord
  belongs_to :medication
end

app/models/llc_service.rb
class LlcService < ApplicationRecord
  has_one :hpc_service, as: :hpc_serviceable, dependent: :destroy
  accepts_nested_attributes_for :hpc_service

  has_many :location_services, as: :location_serviceable, dependent: :destroy
  accepts_nested_attributes_for :location_services, allow_destroy: true, reject_if: :all_blank

  has_many :change_services, as: :change_serviceable, dependent: :destroy
  accepts_nested_attributes_for :change_services, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank

  belongs_to :company
  belongs_to :user
end

app/models/location_service.rb
class LocationService < ApplicationRecord
  belongs_to :location_serviceable, polymorphic: true, optional: true
end

app/models/mar.rb
class Mar < ApplicationRecord
  belongs_to :company
  belongs_to :user
  has_many :medication_items, dependent: :destroy
  accepts_nested_attributes_for :medication_items, allow_destroy: true, reject_if: :all_blank

  has_many :medication_documents, dependent: :destroy
  accepts_nested_attributes_for :medication_documents, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank
end

app/models/medication.rb
class Medication < ApplicationRecord
  belongs_to :company
  belongs_to :user

  has_many :ist_informations, dependent: :destroy
  accepts_nested_attributes_for :ist_informations, allow_destroy: true, reject_if: :all_blank

  MEDICATION_TYPE = ['Oral', 'Inhaler', 'Optic (Rt eye /Lt eye)', 'Rectal', 'Subcutaneous', 'Sublingual', 'Nebulizer', 'Otic(Rt eye /Lt ear)', 'Vaginal', 'Insulin', 'Glucagon', 'EpiPen']

end

app/models/medication_count.rb
class MedicationCount < ApplicationRecord
  belongs_to :company
  belongs_to :user
  has_many :medication_count_items, dependent: :destroy
  accepts_nested_attributes_for :medication_count_items, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank
end

app/models/medication_item.rb
class MedicationItem < ApplicationRecord
  belongs_to :mar
end

app/models/restricted_measure.rb
class RestrictedMeasure < ApplicationRecord
  belongs_to :behavior
end

app/models/signature_list.rb
class SignatureList < ApplicationRecord
  belongs_to :signatureable, polymorphic: true, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  belongs_to :company, optional: true
  has_many :bsp_trainings
  has_many :llc_services
  has_many :medications
  has_many :medication_counts
  has_many :mars
  has_many :behaviors


  def full_name
    if first_name && last_name
      first_name + ' ' + last_name
      else
        first_name ? first_name : last_name
    end
  end
end

app/controllers/llc_services_controller.rb
class LlcServicesController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      @llc_services =  current_company.llc_services
    else
      @llc_services =  current_user.llc_services
    end
  end

  def new
    @llc_service = LlcService.new
    @llc_service.build_hpc_service
    @llc_service.location_services.build
    @llc_service.change_services.build
    @llc_service.signature_lists.build
  end

  def create
    @llc_service =  current_company.llc_services.new(llc_service_params)
    @llc_service.user_id = current_user.id
    if @llc_service.save
      flash[:notice] = "LLC Services is successfully created"
      redirect_to llc_services_path
    else
      flash[:alert] = "Something worng please try again"
      render action: :new
    end
  end


  def edit
    @llc_service = current_company.llc_services.find_by_id(params[:id])
  end

  def show
    @llc_service = current_company.llc_services.find_by_id(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render template: 'llc_services/show', pdf: 'Monthly-service-' + Time.now.strftime('%v %H:%M:%S').to_s,
               layout: 'pdf.html.erb', disposition: 'attachment'
      end
    end
  end

  def update
    @llc_service = current_company.llc_services.find_by_id(params[:id])
    if @llc_service.update_attributes(llc_service_params)
      flash[:notice] = "LLC Services is successfully Saved"
      redirect_to llc_services_path
    else
      flash[:alert] = "Something worng please try again"
      render action: :edit
    end
  end


  def destroy
    @llc_service = current_company.llc_services.find_by_id(params[:id])
    if @llc_service.destroy
      flash[:notice] = "Successfully deleted!"
    else
      flash[:alert] = "Something went wrong, please try again!"
    end
    redirect_to action: :index
  end

  private

  def llc_service_params
    params.require(:llc_service).permit!
  end
end

app/helpers/behaviors_helper.rb
module BehaviorsHelper
end

app/helpers/llc_services_helper.rb
module LlcServicesHelper
end

app/helpers/mars_helper.rb
module MarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/llc_services/_form.html.erb
<%= form_for @llc_service, html: {class: 'fromlist'} do |f| %>
    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
      <div class="form-group" >
        <%= f.label :user_id, "Individual", style: 'opacity: .5;' %><br />
        <%= f.select(:user_id, current_company.individuals.collect { |ind| [ind.full_name, ind.id] }, {}, { :class => 'form-control chosen-select', required: true}) %>
      </div>

      <div class="form-group">
        <%= f.text_field :medicaid_number, class: 'form-control', required: true %>
        <%= f.label :medicaid_number, class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.text_field :location_of_services, class: 'form-control', required: true %>
        <%= f.label :location_of_services, class: 'form-control-placeholder' %>
      </div>
    </div>

    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
      <div class="form-group">
        <%= f.label :service_type, "Service Type", style: 'opacity: .5;' %><br/>
        <%= f.select(:service_type, ['1', '2', '3', '4', '5'], {}, {:class => 'form-control chosen-select', required: true}) %>
      </div>
      <div class="form-group">
        <%= f.text_field :provider_contract, class: 'form-control', required: true %>
        <%= f.label :provider_contract, class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.text_field :date, class: 'form-control datepicker', required: true %>
        <%= f.label :date, class: 'form-control-placeholder' %>
      </div>
    </div>



    <%= f.fields_for :hpc_service do |hpcs| %>
        <div class="col-md-12 col-sm-12 col-lg-12 medicaldics">HPC Services Provided</div>
        <%= render 'shared/hpc_service', hpcs: hpcs %>
    <% end %>

    <div class="col-md-12 col-sm-12 col-lg-12 medicaldics">Locations where other services were provided</div>
    <div class="locations-wrapper">
      <%= f.fields_for :location_services do |ls| %>
          <%= render 'shared/location_services', ls: ls %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-4 col-lg-4 addfilds">
      <a id="location_add" class="addmore-btn" href="javascript:void(0);">
        <%= image_tag 'plus_icon.png' %>Add Location
        Fields ( 2 )
      </a>
    </div>

    <div class="col-md-12 col-sm-12 col-lg-12 medicaldics">Service Fields</div>

    <div class="change-service-wrapper">
      <%= f.fields_for :change_services do |cs| %>
          <%= render 'shared/change_services', cs: cs %>
      <% end %>
    </div>
    <div class="col-md-12 col-sm-12 col-lg-12 addfilds" id="">
      <a id="change_add" class="addmore-btn" href="javascript:void(0);">
        <%= image_tag 'plus_icon.png' %>Add Services
        Fields ( 2 )
      </a>
    </div>



    <div class="col-md-12 col-sm-12 col-lg-12 medicaldics">Signature Fields</div>
    <div class="signature-list-wrapper">
      <%= f.fields_for :signature_lists do |sl| %>
          <%= render 'shared/signature_lists', sl: sl %>
      <% end %>
    </div>
    <div class="col-md-12 col-sm-12 col-lg-12 addfilds">
      <a id="signature_add" class="addmore-btn" href="javascript:void(0);">
        <%= image_tag 'plus_icon.png' %>Add Signature Fields ( 2 )
      </a>
    </div>

    <div class="col-md-12 col-sm-12 savebut">
      <button type="submit" class="btn btn-default">Save</button>
    </div>
<% end %>

<%= render 'shared/signature_modal' %>
<script type="text/javascript">
  $('.chosen-select').chosen({});
  $("#location_add").on("click", function () {
    var serialNumber = new Date().getTime();
    var regexp = new RegExp('serial_number', 'g');
    $('.locations-wrapper').append("<%= escape_javascript(render 'shared/location_service_item').html_safe %>".replace(regexp, serialNumber));
  });

  $("#change_add").on("click", function () {
    var serialNumber = new Date().getTime();
    var regexp = new RegExp('serial_number', 'g');
    $('.change-service-wrapper').append("<%= escape_javascript(render 'shared/change_service_item').html_safe %>".replace(regexp, serialNumber));
  });

  $("#signature_add").on("click", function () {
    var serialNumber = new Date().getTime();
    var regexp = new RegExp('serial_number', 'g');
    $('.signature-list-wrapper').append("<%= escape_javascript(render 'shared/signature_list_item').html_safe %>".replace(regexp, serialNumber));
  });

  $(function () {
    $(document).off('click', '.signature').on('click', '.signature', function () {
      var selector = this.id
      $("#exampleModal").modal().on('shown.bs.modal', function () {
        $(this).off('shown.bs.modal');
        drawSignature('#' + selector);
      });
    });
  });
</script>

app/views/llc_services/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
    <p><h1>Create LLC Services</h1></p>
    <%= render 'form' %>
  </div>
</div>

app/views/llc_services/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
    <div class="panel panel-default">
      <div class="panel-heading indiviuals_list">
        Services LLC

      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
              <th>S. No.</th>
              <th>Individual Name</th>
              <th>Date of Training</th>
              <th>Last Edited</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @llc_services.each_with_index  do |llc_service, i| %>
              <tr>
                <td><%= i + 1 %></td>
                <td><%= llc_service.user.full_name if llc_service.user.present? %></td>
                <td><%= llc_service.date %></td>
                <td><%= llc_service.user_id %></td>
                <td><%= link_to edit_llc_service_path(llc_service) do %>
                      <%= image_tag 'setting.png' %> Edit
                  <% end %>
                </td>
                <td>
                  <%= link_to llc_service_path(llc_service) do %>
                      <i class="fa fa-eye"></i> View
                  <% end %>
                </td>
                <td>
                  <% if current_user.admin? %>
                  <%= link_to  llc_service_path(llc_service,authenticity_token: form_authenticity_token), method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <%= image_tag 'delete.png' %> Delete
                  <% end %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>


      <!-- /.panel-body -->
    </div>
    <%= link_to 'Add New Entry', new_llc_service_path, class: 'btn add_entry' %>
  </div>
  <!-- /.row -->
</div>

app/views/llc_services/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
    <p><h1>Create LLC Services</h1></p>
    <%= render 'form' %>
  </div>
</div>

app/views/llc_services/show.html.erb
<div id="page-wrapper">
<div class="row">
<div class="headline text-center">
  <h4>Quality Comfort Living & Services LLC</h4>
</div>
<div class="space"></div>
<table class="table medication-count-table mar-table">
  <!--<caption class="text-center lead">Medication Administration Record (MAR)</caption>-->
  <thead>
  <tr>
    <th class="r-border-transparent" rowspan="1" colspan="20">
      Monthly Service Documentation
    </th>
    <th class="l-border-transparent" rowspan="1" colspan="14">
      Service Documentation Key:
    </th>
  </tr>
  <tr>
    <th class="vertical-align-top" colspan="6" style="border-right: none">
      <div class="monthly-service">
        <div class=" mb-20">
          <ul class="common-ul-style doc-info">
            <li>
              Individual's Name:
              <span><%= @llc_service.user.full_name  if @llc_service.user.present? %></span>
            </li>
            <li>
              Medicaid #
              <span><%= @llc_service.medicaid_number %></span>
            </li>
            <li>
              Location of Service:
              <span><%= @llc_service.location_of_services %></span>
            </li>
          </ul>
        </div>
      </div>
      <div class="hints clearfix">
        <div class="pull-left">Group Size 1</div>
        <div class="pull-right">
          <span>Times of HPC Services: M-F 2:30p-8:30a; </span>
          <span>24hrs per day Sat, </span>
          <span>Sun (All other times and days are as needed.) </span>
        </div>
      </div>
    </th>

    <th class="vertical-align-top" colspan="14" style="border-left: none">
      <div class="monthly-service">
        <div class="row mb-20">
            <ul class="common-ul-style doc-info">
              <li>
                Type of Services:
                <span><%= @llc_service.service_type %></span>
              </li>
              <li>
                Provider Contract:
                <span><%= @llc_service.provider_contract %></span>
              </li>
              <li>
                 Date:
                <span><%= @llc_service.date %></span>
              </li>
            </ul>
        </div>
      </div>
    </th>
    <th colspan="14">
      <table class="table table-borderless">
        <tbody>
        <tr>
          <td colspan="3">Staff Initials = Service Delivered</td>
        </tr>
        <tr>
          <td>F = With Family </td>
          <td>O = Other (Document reason in notes)</td>
          <td>S = Sick </td>
        </tr>
        <tr>
          <td>H = Hospitalization</td>
          <td>R = Refusal of services </td>
          <td>NA = Not applicable</td>
        </tr>
        </tbody>
      </table>
      <div class="service-key">
        <i>Staff please document why services were not provided in notes and document the reason code above.</i>
      </div>
    </th>
  </tr>
  <tr>
    <th class="min-width-250"><strong>HPC Services Provided</strong></th>
    <th>Frequency</th>
    <th>Duration</th>
    <th>1</th>
    <th>2</th>
    <th>3</th>
    <th>4</th>
    <th>5</th>
    <th>6</th>
    <th>7</th>
    <th>8</th>
    <th>9</th>
    <th>10</th>
    <th>11</th>
    <th>12</th>
    <th>13</th>
    <th>14</th>
    <th>15</th>
    <th>16</th>
    <th>17</th>
    <th>18</th>
    <th>19</th>
    <th>20</th>
    <th>21</th>
    <th>22</th>
    <th>23</th>
    <th>24</th>
    <th>25</th>
    <th>26</th>
    <th>27</th>
    <th>28</th>
    <th>29</th>
    <th>30</th>
    <th>31</th>
  </tr>
  </thead>
  <tbody>
  <% @llc_service.hpc_service.attributes.except("id","hpc_serviceable_id", "hpc_serviceable_type", "created_at", "updated_at").each do |key, value| %>
      <tr>
        <td class="flexible-td"><%= value %></td>
        <td>Up to Daily</td>
        <td>Span</td>
        <td>KD</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>
<!-- Quality Comfort Living & Services LLC -->

<div class="space"></div>
<!-- Locations where other services were provided -->
<h4 class="text-center">Locations where other services were provided</h4>
<table class="table medication-count-table">
  <thead>
  <tr>
    <th>Location</th>
    <th>Initials</th>
    <th>Date</th>
  </tr>
  </thead>
  <tbody>
  <% @llc_service.location_services.each do |ls| %>
  <tr>
    <td>
      <%= ls.location %>
    </td>
    <td>
      <%= ls.initials %>
    </td>
    <td>
      <%= ls.date %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
<!-- Locations where other services were provided -->

<div class="space"></div>
<!-- Notes: Please note: -->
<h4 class="text-center">Notes: Please note: (any changes in services or service delivery, new behavior/medical issues or any new discoveries, and reason codes.</h4>
<table class="table medication-count-table">
  <thead>
  <tr>
    <th>Date</th>
    <th>Description</th>
  </tr>
  </thead>
  <tbody>
  <% @llc_service.change_services.each do |cs| %>
  <tr>
    <td><%= cs.date %></td>
    <td><%= cs.description %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<!-- Notes: Please note: -->

<div class="space"></div>
<!-- Signature -->
<h4 class="text-center">Notes: Please note: (any changes in services or service delivery, new behavior/medical issues or any new discoveries, and reason codes.</h4>
<table class="table medication-count-table">
  <thead>
  <tr>
    <th>Signature</th>
    <th>Initials</th>
  </tr>
  </thead>
  <tbody>
  <% @llc_service.signature_lists.each do |sl| %>
  <tr>
    <td><%= image_tag sl.signature, size: 125 %></td>
    <td><%= sl.initials %></td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>
<script type="text/javascript">
  $(".save-as-pdf" ).click(function() {
    window.location.replace("<%= llc_service_path(@llc_service, format: :pdf) %>")
  });
</script>

app/views/llc_services/show.pdf.erb
<div id="page-wrapper">
  <div class="row">
    <div class="headline text-center">
      <h4>Quality Comfort Living & Services LLC</h4>
    </div>
    <div class="space"></div>
    <table class="table medication-count-table mar-table">
      <!--<caption class="text-center lead">Medication Administration Record (MAR)</caption>-->
      <thead>
      <tr>
        <th class="r-border-transparent" rowspan="1" colspan="20">
          Monthly Service Documentation
        </th>
        <th class="l-border-transparent" rowspan="1" colspan="14">
          Service Documentation Key:
        </th>
      </tr>
      <tr>
        <th class="vertical-align-top" colspan="6" style="border-right: none">
          <div class="monthly-service">
            <div class=" mb-20">
              <ul class="common-ul-style doc-info">
                <li>
                  Individual's Name:
                  <span style="width: 50%;text-align: left;"><%= @llc_service.user.full_name  if @llc_service.user.present? %></span>
                </li>
                <li>
                  Medicaid #
                  <span><%= @llc_service.medicaid_number %></span>
                </li>
                <li>
                  Location of Service:
                  <span><%= @llc_service.location_of_services %></span>
                </li>
              </ul>
            </div>
          </div>
          <div class="hints clearfix">
            <div class="pull-left">Group Size 1</div>
            <div class="pull-right">
              <span>Times of HPC Services: M-F 2:30p-8:30a; </span>
              <span>24hrs per day Sat, </span>
              <span>Sun (All other times and days are as needed.) </span>
            </div>
          </div>
        </th>

        <th class="vertical-align-top" colspan="14" style="border-left: none">
          <div class="monthly-service">
            <div class="row mb-20">
              <ul class="common-ul-style doc-info">
                <li>
                  Type of Services:
                  <span><%= @llc_service.service_type %></span>
                </li>
                <li>
                  Provider Contract:
                  <span><%= @llc_service.provider_contract %></span>
                </li>
                <li>
                  Date:
                  <span><%= @llc_service.date %></span>
                </li>
              </ul>
            </div>
          </div>
        </th>
        <th colspan="14">
          <table class="table table-borderless">
            <tbody>
            <tr>
              <td colspan="3">Staff Initials = Service Delivered</td>
            </tr>
            <tr>
              <td>F = With Family </td>
              <td>O = Other (Document reason in notes)</td>
              <td>S = Sick </td>
            </tr>
            <tr>
              <td>H = Hospitalization</td>
              <td>R = Refusal of services </td>
              <td>NA = Not applicable</td>
            </tr>
            </tbody>
          </table>
          <div class="service-key">
            <i>Staff please document why services were not provided in notes and document the reason code above.</i>
          </div>
        </th>
      </tr>
      <tr>
        <th class="min-width-250"><strong>HPC Services Provided</strong></th>
        <th>Frequency</th>
        <th>Duration</th>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>10</th>
        <th>11</th>
        <th>12</th>
        <th>13</th>
        <th>14</th>
        <th>15</th>
        <th>16</th>
        <th>17</th>
        <th>18</th>
        <th>19</th>
        <th>20</th>
        <th>21</th>
        <th>22</th>
        <th>23</th>
        <th>24</th>
        <th>25</th>
        <th>26</th>
        <th>27</th>
        <th>28</th>
        <th>29</th>
        <th>30</th>
        <th>31</th>
      </tr>
      </thead>
      <tbody>
      <% @llc_service.hpc_service.attributes.except("id","hpc_serviceable_id", "hpc_serviceable_type", "created_at", "updated_at").each do |key, value| %>
          <tr>
            <td class="flexible-td"><%= value %></td>
            <td>Up to Daily</td>
            <td>Span</td>
            <td>KD</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <!-- Quality Comfort Living & Services LLC -->

    <div class="space"></div>
    <!-- Locations where other services were provided -->
    <h4 class="text-center">Locations where other services were provided</h4>
    <table class="table medication-count-table">
      <thead>
      <tr>
        <th>Location</th>
        <th>Initials</th>
        <th>Date</th>
      </tr>
      </thead>
      <tbody>
      <% @llc_service.location_services.each do |ls| %>
          <tr>
            <td>
              <%= ls.location %>
            </td>
            <td>
              <%= ls.initials %>
            </td>
            <td>
              <%= ls.date %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <!-- Locations where other services were provided -->

    <div class="space"></div>
    <!-- Notes: Please note: -->
    <h4 class="text-center">Notes: Please note: (any changes in services or service delivery, new behavior/medical issues or any new discoveries, and reason codes.</h4>
    <table class="table medication-count-table">
      <thead>
      <tr>
        <th>Date</th>
        <th>Description</th>
      </tr>
      </thead>
      <tbody>
      <% @llc_service.change_services.each do |cs| %>
          <tr>
            <td><%= cs.date %></td>
            <td><%= cs.description %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <!-- Notes: Please note: -->

    <div class="space"></div>
    <!-- Signature -->
    <h4 class="text-center">Notes: Please note: (any changes in services or service delivery, new behavior/medical issues or any new discoveries, and reason codes.</h4>
    <table class="table medication-count-table">
      <thead>
      <tr>
        <th>Signature</th>
        <th>Initials</th>
      </tr>
      </thead>
      <tbody>
      <% @llc_service.signature_lists.each do |sl| %>
          <tr>
            <td><%= image_tag sl.signature, size: 125 %></td>
            <td><%= sl.initials %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>