config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations",  confirmations: 'confirmations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get 'load_cities' => 'welcome#load_cities'
  get 'load_state' => 'welcome#load_state'

  resources :bsp_trainings
  resources :llc_services
  resources :medications
  resources :medication_counts
  resources :mars
  resources :behaviors

  resources :users do
    get 'settings'
    get 'edit_password', on: :collection
    put 'update_password', on: :collection
    post 'add_individual', on: :collection
    put 'update_individual', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/behavior.rb
class Behavior < ApplicationRecord
  belongs_to :user

  has_one :restricted_measure, dependent: :destroy
  accepts_nested_attributes_for :restricted_measure

  has_many :behavior_outcomes, dependent: :destroy
  accepts_nested_attributes_for :behavior_outcomes, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank
end

app/models/behavior_outcome.rb
class BehaviorOutcome < ApplicationRecord
  belongs_to :behavior
end

app/models/bsp_training.rb
class BspTraining < ApplicationRecord
   belongs_to :company
  belongs_to :user
end

app/models/change_service.rb
class ChangeService < ApplicationRecord
  belongs_to :change_serviceable, polymorphic: true, optional: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :bsp_trainings
  has_many :llc_services
  has_many :medications
  has_many :medication_counts
  has_many :mars
  has_many :behaviors

  def individuals
    self.users.where(admin: false)
  end
end

app/models/hpc_service.rb
class HpcService < ApplicationRecord
  belongs_to :hpc_serviceable, polymorphic: true, optional: true
end

app/models/ist_information.rb
class IstInformation < ApplicationRecord
  belongs_to :medication
end

app/models/llc_service.rb
class LlcService < ApplicationRecord
  has_one :hpc_service, as: :hpc_serviceable, dependent: :destroy
  accepts_nested_attributes_for :hpc_service

  has_many :location_services, as: :location_serviceable, dependent: :destroy
  accepts_nested_attributes_for :location_services, allow_destroy: true, reject_if: :all_blank

  has_many :change_services, as: :change_serviceable, dependent: :destroy
  accepts_nested_attributes_for :change_services, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank

  belongs_to :company
  belongs_to :user
end

app/models/location_service.rb
class LocationService < ApplicationRecord
  belongs_to :location_serviceable, polymorphic: true, optional: true
end

app/models/mar.rb
class Mar < ApplicationRecord
  belongs_to :company
  belongs_to :user
  has_many :medication_items, dependent: :destroy
  accepts_nested_attributes_for :medication_items, allow_destroy: true, reject_if: :all_blank

  has_many :medication_documents, dependent: :destroy
  accepts_nested_attributes_for :medication_documents, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank
end

app/models/medication.rb
class Medication < ApplicationRecord
  belongs_to :company
  belongs_to :user

  has_many :ist_informations, dependent: :destroy
  accepts_nested_attributes_for :ist_informations, allow_destroy: true, reject_if: :all_blank

  MEDICATION_TYPE = ['Oral', 'Inhaler', 'Optic (Rt eye /Lt eye)', 'Rectal', 'Subcutaneous', 'Sublingual', 'Nebulizer', 'Otic(Rt eye /Lt ear)', 'Vaginal', 'Insulin', 'Glucagon', 'EpiPen']

end

app/models/medication_count.rb
class MedicationCount < ApplicationRecord
  belongs_to :company
  belongs_to :user
  has_many :medication_count_items, dependent: :destroy
  accepts_nested_attributes_for :medication_count_items, allow_destroy: true, reject_if: :all_blank

  has_many :signature_lists, as: :signatureable, dependent: :destroy
  accepts_nested_attributes_for :signature_lists, allow_destroy: true, reject_if: :all_blank
end

app/models/medication_item.rb
class MedicationItem < ApplicationRecord
  belongs_to :mar
end

app/models/restricted_measure.rb
class RestrictedMeasure < ApplicationRecord
  belongs_to :behavior
end

app/models/signature_list.rb
class SignatureList < ApplicationRecord
  belongs_to :signatureable, polymorphic: true, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  belongs_to :company, optional: true
  has_many :bsp_trainings
  has_many :llc_services
  has_many :medications
  has_many :medication_counts
  has_many :mars
  has_many :behaviors


  def full_name
    if first_name && last_name
      first_name + ' ' + last_name
      else
        first_name ? first_name : last_name
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = User.new
  end

  def add_individual
    @user = current_company.users.new(user_params)
    random_number = rand.to_s[2..11]
    @user.password = random_number
    @user.password_confirmation = random_number
    @user.confirmed_at = Time.now
    if @user.save
      UserMailer.welcome_email(@user).deliver
      flash[:notice] = "Indviduals is successfully created"
      redirect_to root_path
    else
      flash[:alert] = "Something worng please try again"
      render action: :new
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update_individual
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "Indviduals is successfully Saved"
      redirect_to root_path
    else
      flash[:alert] = "Something worng please try again"
      render action: :edit
    end
  end



  def index
    @users = current_company.individuals
    if params[:search].present?
      search =  params[:search]
      @users = @users.where("first_name like ? or last_name like ? or state like ? or email like ? or medicare_number like ? or medicaid_number like ?",
                            "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" , "%#{search}%" , "%#{search}%")
    end
  end

  def settings

  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
        flash[:notice] = "Password Successfully Updated"
        redirect_to root_path
    else
      flash[:alert] = "Something worng please try again"
      render "edit_password"
    end
  end

  private

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/behaviors_helper.rb
module BehaviorsHelper
end

app/helpers/mars_helper.rb
module MarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_form.html.erb
    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
      <div class="form-group">
        <%= f.text_field :individual_id, class: 'form-control', required: true%>
        <%= f.label :individual_id, 'Individual Id', class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.text_field :last_name,class: 'form-control', required: true %>
        <%= f.label :last_name,  class: 'form-control-placeholder' %>
      </div>

      <label class="radio-inline">
        <%= f.radio_button :title, 'MD' %> MD
      </label>
      <label class="radio-inline">
        <%= f.radio_button :title, 'DD' %> DD
      </label>
      <div class="form-group">
        <%= f.text_field :telephone,class: 'form-control',required: true %>
        <%= f.label :telephone, 'Telephone', class: 'form-control-placeholder' %>
      </div>

      <div class="form-group">
        <%= f.text_field :medicare_number,class: 'form-control', required: true %>
        <%= f.label :medicare_number,  class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.text_field :tabs_id,class: 'form-control', required: true %>
        <%= f.label :tabs_id,'TABS ID',  class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.label :state, "State", style: 'opacity: .5;' %><br />
        <%= f.select(:state, [], {}, { :class => 'form-control chosen-select', required: true}) %>
      </div>
      <div class="form-group">
        <%= f.text_field :address_2,class: 'form-control', required: true %>
        <%= f.label :address_2,  class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.label :ethnicity, "ethnicity", style: 'opacity: .5;' %><br />
        <%= f.select(:ethnicity, ['White','Black', 'Brown'], {}, { :class => 'form-control chosen-select', required: true}) %>
      </div>
    </div>
    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
      <div class="form-group">
        <%= f.text_field :first_name,class: 'form-control', required: true %>
        <%= f.label :first_name,  class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.email_field :email,class: 'form-control', required: true %>
        <%= f.label :email,'Email Address',  class: 'form-control-placeholder' %>
      </div>
      <label class="radio-inline">
        <%= f.radio_button :gender, 'male' %> Male
      </label>
      <label class="radio-inline">
        <%= f.radio_button :gender, 'female' %> Female
      </label>
      <div class="form-group">
        <%= f.text_field :phone,class: 'form-control', required: true %>
        <%= f.label :phone,'Cell Phone',  class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.text_field :medicaid_number,class: 'form-control', required: true %>
        <%= f.label :medicaid_number,  class: 'form-control-placeholder' %>
      </div>
      <div class="form-group" id="city-load">
        <%= f.label :country, "Country", style: 'opacity: .5;' %><br />
        <%= f.select(:country, CS.countries.collect { |key, val| [val, key] }, {}, { :class => 'form-control chosen-select', required: true}) %>
      </div>
      <div class="form-group">
        <%= f.text_field :zip,class: 'form-control', required: true %>
        <%= f.label :zip,  class: 'form-control-placeholder' %>
      </div>

      <div class="form-group">
        <%= f.text_field :address_1,class: 'form-control', required: true %>
        <%= f.label :address_1,  class: 'form-control-placeholder' %>
      </div>

      <div class="form-group">
        <label class="radio-inline">
          <%= f.check_box :active,class: 'form-controls' %>
          <%= f.label :active %>
        </label>
      </div>
    </div>
    <div class="col-md-12 col-sm-12 savebut">
      <button type="submit" class="btn btn-default">Save</button>
    </div>

    <script type="application/javascript">
      $(function() {
        var countrySelector = $('#user_country');
        var state = "<%= f.object.state %>";
        $('.datepicker').datepicker();
        $('.chosen-select').chosen({});
        state_select(countrySelector.val(), state);
        countrySelector.change(function() {
          var country = $(this).val()
          state_select(country, '');
        });
      })
        function state_select(country, state) {
          if(country) {
            $.ajax({
              type: 'get',
              url: '<%= load_state_path %>',
              data: {country: country, id: "user_state", state: state},
              dataType: 'script',
            });
          }
        }
    </script>

app/views/users/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
    <p><h1>Edit Individual</h1></p>
    <%= form_for(@user, url: update_individual_user_path(@user), method: 'PUT',html: {class: 'fromlist'}) do |f| %>
        <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/users/edit_password.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
        <%= form_for(@user, url: update_password_users_path, method: "put", html: {class: 'fromlist'}) do |f| %>

        <div class="form-group">
          <%= f.password_field :password, autocomplete: "off",class: 'form-control' %>
          <%= f.label :password, class: 'form-control-placeholder' %>
        </div>
        <div class="form-group">
          <%= f.password_field :password_confirmation, autocomplete: "off",class: 'form-control'%>
          <%= f.label :password_confirmation, class: 'form-control-placeholder' %>
        </div>
            <button type="submit" class="btn btn-default">Update Password</button>
        <% end %>
      </div>
</div>

app/views/users/index.html.erb
<div id="page-wrapper">
    <div class="row">
      <p>&nbsp;</p>
      <div class="panel panel-default">
        <div class="panel-heading indiviuals_list">
          <span>Individuals List</span>
          <ul class="list_select">
            <li>
              <select class="form-control">
                <option>S.NO.</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </li>
            <li>
              <select class="form-control">
                <option>Status</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </li>
            <li>
              <select class="form-control">
                <option>Gender</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </li>
          </ul>
          <div class="searchbox">
            <div class="form-group input-group">
              <%= image_tag 'search.png' %>
              <%= form_tag(users_path, method: :get)  do %>
              <%= text_field_tag(:search, params[:search], class: 'form-control' )%>
              <% end %>
            </div></div>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th>S. No.</th>
                <th>Individual ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Status</th>
                <% if current_user.admin? %>
                <th colspan="2">Action</th>
                <% end %>
              </tr>
              </thead>
              <tbody>
              <% @users.each_with_index do |user ,i| %>
                  <tr>
                    <td><%= i + 1 %></td>
                    <td><%= user.id %></td>
                    <td><%= user.first_name %></td>
                    <td><%= user.last_name %></td>
                    <td>
                      <% if user.active? %>
                          <%= image_tag 'active.png' %>
                      <% else %>
                        Inactive
                      <% end %>
                    </td>
                    <% if current_user.admin? %>
                        <td><%= link_to edit_user_path(user) do %>
                              <%= image_tag 'setting.png' %> Edit
                          <% end %></td>
                    <% end %>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
          <!-- /.table-responsive -->
        </div>


        <!-- /.panel-body -->
      </div>
      <%= link_to 'Add New Entry', new_user_path, class: 'btn add_entry' if current_user.admin? %>
    </div>
    <!-- /.row -->
  </div>

app/views/users/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
    <p><h1>Create Individual</h1></p>
    <%= form_for(@user, url: add_individual_users_path, method: 'POST',html: {class: 'fromlist'}) do |f| %>
        <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/users/settings.html.erb
<div id="page-wrapper">
  <div class="row">
    <p>&nbsp;</p>
    <div class="listtime">
      <ul>
        <li><%= image_tag 'billing1.png' %></li>
        <li><%= image_tag 'billing2.png' %></li>
        <li><%= image_tag 'billing3.png' %></li>
        <li><%= image_tag 'billing4.png' %></li>
        <li><%= link_to edit_password_users_path  do %>
              <%= image_tag 'billing5.png' %>
          <% end %>
        </li>
        <li><%= image_tag 'billing6.png' %></li>
      </ul>

      <!-- /.panel-body -->
    </div>

  </div>
  <!-- /.row -->
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_sigin_form.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'frombox'}) do |f| %>
    <div class="form-group">
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', placeholder: 'Email Address ' %>
    </div>
    <div class="form-group">
      <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Password ' %>
    </div>
    <button type="submit" class="btn btn-default">Sign In</button>
    <div class="checkbox">

      Need Help?

    </div>
<% end  %>

app/views/users/shared/_signup_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'fromlist'}) do |f| %>
    <div class="clearfix">
    <%= f.fields_for :company do |ff| %>
        <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
          <div class="form-group">
            <%= ff.label :company_type, "User Type", style: 'opacity: .5;' %><br />
            <%= ff.select(:company_type, ['Service Provider','Individual'], {}, { :class => 'form-control chosen-select', required: true}) %>
          </div>

          <div class="form-group">
            <%= ff.label :state, "State", style: 'opacity: .5;' %><br />
            <%= ff.select(:state, [], {}, { :class => 'form-control chosen-select', required: true}) %>
          </div>
          <div class="form-group">
            <%= ff.text_field :phone, class: 'form-control', required: true %>
            <%= ff.label :phone, class: 'form-control-placeholder' %>
          </div>

          <div class="form-group">
            <%= ff.text_field :address_2,class: 'form-control', required: true %>
            <%= ff.label :address_2, class: 'form-control-placeholder' %>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
          <div class="form-group" id="city-load">
            <%= ff.label :country, "Country", style: 'opacity: .5;' %><br />
            <%= ff.select(:country, CS.countries.collect { |key, val| [val, key] }, {}, { :class => 'form-control chosen-select', required: true}) %>
          </div>
          <div class="form-group" id="city-load">
            <%= ff.label :city, "City", style: 'opacity: .5;' %><br />
            <%= ff.select(:city, [], {}, { :class => 'form-control chosen-select', required: true}) %>
          </div>

          <div class="form-group">
            <%= ff.text_field :address_1,class: 'form-control' %>
            <%= ff.label :address_1, class: 'form-control-placeholder' %>
          </div>

          <div class="form-group">
            <%= ff.text_field :zip,class: 'form-control' %>
            <%= ff.label :zip, class: 'form-control-placeholder' %>
          </div>
        </div>
    <% end %>
    </div>

    <div class="clearfix">
    <div class="col-md-12 col-sm-12 col-lg-12 medicaldics">Account Details</div>

    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
      <div class="form-group">
        <%= f.email_field :email ,class: 'form-control'%>
        <%= f.label :email, class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.text_field :last_name,class: 'form-control'%>
        <%= f.label :last_name, class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, autocomplete: "off",class: 'form-control'%>
        <%= f.label :password_confirmation, class: 'form-control-placeholder' %>
      </div>
    </div>

    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
      <div class="form-group">
        <%= f.text_field :first_name,class: 'form-control'%>
        <%= f.label :first_name, class: 'form-control-placeholder' %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, autocomplete: "off",class: 'form-control' %>
        <%= f.label :password, class: 'form-control-placeholder' %>
      </div>
    </div>
    </div>

      <div class="checkleft" style="margin-left: 40px;">
        <div class="radio">
          <input name="optionsRadios" id="optionsRadios1" value="option1" checked="" type="radio">
          <label for="optionsRadios1">I agree to the Health Terms of Service & I certify that I have read and agree the Health Privacy Policy & Health Business Associate Agreement </label>
        </div>
      </div>

    <div class="col-md-12 col-sm-12 savebut">
      <button type="submit" class="btn btn-default">Sign Up</button>
    </div>
<%end%>

<script type="text/javascript">
  $('.chosen-select').chosen({

  });

    $('#user_company_state').change(function() {
      var state = $(this).val()
      var country = $('#user_company_country').val();
      $.ajax({
        type: 'get',
        url: '<%= load_cities_path %>',
        data: {state: state, country: country},
        dataType: 'script',
      });
    });

  $('#user_company_country').change(function() {
    var country = $(this).val()
    $.ajax({
      type: 'get',
      url: '<%= load_state_path %>',
      data: {country: country, id: 'user_company_state'},
      dataType: 'script',
    });
  });
</script>